name: Test jto-env on Mac, Linux, Windows

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  runtests:
    name: Ex10 (${{ matrix.os }}, Miniforge)
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu", "macos", "windows"]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4

      - name: Install conda envt w 
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment.yml
          environment-name: jto-env
          miniforge-version: latest
          cache-environment: true
          post-cleanup: 'all'
#      - name: Conda List
#      - run: conda list
#      - run: python -c "import dataprep"
#      - run: python -c "import statsmodels"
